### ISSUE TITLE
Pegar horário do intercamping

### ISSUE THREAD

**Issue by jppgomes** [fga-eps-mds/2019.1-Tino#38]
## Descrição 
**Eu**, como usuário, **desejo** conseguir o horário do próximo intercamping

## Tarefas 
- [x] Solicitar o horário do intercamping
- [x] Salvar no mongo

## Critérios de aceitação
- [x] O sistema deve procurar no banco a lista com os horários do intercampi. 
- [x] O sistema deve enviar ao usuário o horário, origem e destino do próximo intercampi.

**Comment by RochaCarla** [comment]
cade criterios de aceitação?!!!!!
