### ISSUE TITLE
Consultar contato do professor

### ISSUE THREAD

**Issue by jppgomes** [fga-eps-mds/2019.1-Tino#44]
## Descrição 
**Eu**, como usuário, **desejo** saber o contato do professor (email) para que possa entrar em contato.

## Descrição
 - [x] Dado que o usuário diga o nome do professor, o bot deve executar uma ação personalizada e retornar a informação.

## Criterios de aceitaçao
- [x] Retornar email do professor
- [x] Retornar sala de atendimento

**Comment by lbrunofidelis** [comment]
Adicionar mensagem de erro ao usuário quando não encontrar o professor, atualmente não responde nada.
