### ISSUE TITLE
Importação de CSV

### ISSUE THREAD

**Issue by lbrunofidelis** [fga-eps-mds/2019.1-Tino#50]
### Descrição     
Há a necessidade de se atualizar os dados referente à funcionalidade de Informações sobre os Professores. Porém, a atualização desses dados é feita manualmente por meio de um arquivo CSV que deve ser importado pelo projeto e lido para persistir os dados no banco.

### Critérios de aceitação
- [x] Ler arquivo CSV em um diretório do projeto
- [x] Salvar dados no banco
- [x] Retornar quantidade de registros salvos

**Comment by lucaslop** [comment]
Eu e @lbrunofidelis fizemos a leitura do csv, convertemos para json e a verificação de cada campo ( name, room, email). Porém, na hora de verificar se há algum espaço em branco nos valores de cada campo, não analisa tudo de uma vez e ta ocorrendo o seguinte problema:

se tiver um espaço em branco no incio , para de adicionar no baco de dados

se tiver um espaço em branco no meio ou final, ele adiciona até encontrar esse espaço branco. Como fazemos para verificar tudo? @jppgomes

**Comment by jppgomes** [comment]
A solução pode ser verificar se existe algum registro após a linha em branco, se não existir significa que está no final do csv.

**Comment by lucaslop** [comment]
OK. Obrigado
