### ISSUE TITLE
Refatorar intercamping

### ISSUE THREAD

**Issue by jppgomes** [fga-eps-mds/2019.1-Tino#61]
Refatorar feature do intercamping

- [x] Entities corretas
- [x] Conversação validada pelo processo de testes de impacto

**Comment by lucaslop** [comment]
Ao pedir o próximo intercampi, o retorno sempre é não tem mais disponível, mesmo sendo dentro do horário de intercampi disponíveis. Ao consultar o banco, o banco fica sem nenhum dado sobre o intercampi.
