### ISSUE TITLE
Criação de testes de conexão com o banco de dados

### ISSUE THREAD

**Issue by henriquedutra** [fga-eps-mds/2019.1-Tino#73]
## Descrição
Visando garantir a qualidade das conexões com o MongoDB, serão elaborados novos testes envolvendo cada uma das funcionalidades presentes no ChatBot que dependem diretamente do Mongo para seu correto funcionamento.Serão testados se os dados recebidos do banco estão no formato adequado e  e com os dados consistentes.
## Critérios de aceitação
- [x] Utilizar o pytest para testar as funcionalidades dependentes do mongo. 
- [x] Garantir que os dados estão vindo no formato correto.
- [x] Executar com sucesso todos os testes.

**Comment by lucasqmc** [comment]
Issue fechada, testes concluidos com sucesso
