### ISSUE TITLE
Refatoração de testes professor e microserviços

### ISSUE THREAD

**Issue by henriquedutra** [fga-eps-mds/2019.1-Tino#74]
## Descrição 
Realizar testes visando garantir o bom funcionamento da funcionalidade dos professores e dos microserviços .
## Critérios de aceitação
 - [x] Garantir a qualidade do funcionamento da funcionalidade dos professores atraves de testes acerca dos métodos envolvidos. 
 - [x] Garantir a qualidade do funcionamento dos microserviços atraves de testes acerca dos métodos envolvidos.

**Comment by lucasqmc** [comment]
Issue fechada, testes realizados com sucesso.
