### ISSUE TITLE
Explorar fluxo de menu de botões do Telegram

### ISSUE THREAD

**Issue by henriquedutra** [fga-eps-mds/2019.1-Tino#77]
Integrar as opções de menu de botões do Telegram com a opção de ajuda do Bot, algo que foi retornado por testers para melhorar o fluxo de conversação.

- [x] Resposta no \ajuda
- [x] Display do menu corretamente
- [x] Fluxo completo de todas as respostas
- [x] Personalidade inetgrada

**Comment by lbrunofidelis** [comment]
Fechando a issue, alterações já implementadas e aceitas no PR https://github.com/fga-eps-mds/2019.1-Tino/pull/79
